shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

platform:
  - Win32
  - x64

configuration:
  - debug
  - release

build:
  project: ./projects/$(TOOLSET)/fts_console.sln
