shallow_clone: true

version: 1.0.{build}

environment:
  matrix:
  - toolset: vs2017
    os: Visual Studio 2017

  - toolset: vs2015
    os: Visual Studio 2015

  - toolset: vs2013
    os: Visual Studio 2015

  - toolset: vs2012
    os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - debug
  - release

artifacts:
  - path: fts_remote_console_windows*.zip
    name: to_publish

build:
  verbosity: minimal
  project: ./projects/$(toolset)/fts_console.sln

after_build:
  - ps: IF ($env:platform -eq "Win32") {$env:makeplatform = "x32"} ELSE {$env:makeplatform = $env:platform}
  - 7z a fts_remote_console_windows_%toolset%.zip "projects\%toolset%\bin\%makeplatform%_%configuration%\example_game" "projects\%toolset%\bin\%makeplatform%_%configuration%\fts_remote_console"

deploy:
  - provider: S3
    access_key_id:
      secure: FtiBYbH6yZjcLA1oJdUNITGtgT3rrSQhnjuQO3lXZVI=
    secret_access_key: 
      secure: FfuP2INZ8TRnh6CjJH1v/blTOrs1vVDgYjpd6NIKT+UQtWv/y/KYaRrx4MTkQMId
    region: us-east-1
    set_public: true
    bucket: forrestthewoods.binaries
    folder: fts_remote_console
    artifact: to_publish
    on:
      branch: master
      platform: x64
      configuration: release
      toolset: vs2017
