shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

platform:
  - Win32
  - x64

configuration:
  - debug
  - release

artifacts:
  - path: projects\vs*\bin\**\fts_remote_console\*.exe
    name: to_publish

  - path: projects\vs*\bin\**\example_game\*.exe
    name: to_publish

build:
  verbosity: minimal
  project: ./projects/$(TOOLSET)/fts_console.sln

version: 1.0.{build}

deploy:
  - provider: S3
    access_key_id:
      secure: yCbsU/ZSm/siW4TnxDO1DC8VicUM8oqcSwibd8QG0yQ=
    secret_access_key: 
      secure: fEw96fpkfKkjBR3sT/ofcDLSB6mBUbDsLX4EiuzYhwXeIaH98sqPzEoxAeOqa/h7KCxBINxYcJ8YgtyRPU9ZFjb3HGA9xyEOrbN6SEF8AcA=
    region: us-east-1
    set_public: true
    bucket: forrestthewoods.binaries
    folder: fts_remote_console
    artifact: to_publish