language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - compiler: clang
      os: osx
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

script:
  - cd projects/gmake
  - make all

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3