language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: clang
      os: osx
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

script:
  - cd projects/gmake
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make all CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make all; fi

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3