language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

before_script: cd projects/gmake

script:
  - make build

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3