language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

before_script: ls && cd projects/make

script:
  - make all

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3