language: cpp

matrix:
  include:
      - os: linux
        compiler: gcc
        env: CXX_COMPILER="g++-4.9" CC_COMPILER="gcc-4.9"

      - os: linux
        compiler: clang
        env: CXX_COMPILER="clang++" CC_COMPILER="clang"
      
      - os: osx
        compiler: gcc
        env: CXX_COMPILER="g++-4.9" CC_COMPILER="gcc-4.9"
        osx_image: xcode8.2

      - os: osx
        compiler: clang
        env: CXX_COMPILER="clang++" CC_COMPILER="clang"
        osx_image: xcode8.2
        
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
    - linux-libc-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - freeglut3-dev

branches:
  only:
    - master

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make config=release64 CXX=${CXX_COMPILER} CC=${CC_COMPILER}; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make config=release64 CXX=${CXX_COMPILER} CC=${CC_COMPILER}; fi

notifications:
  email: false

