language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      os: osx
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

script:
  - cd projects/gmake
  - make all

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode7.3