language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
    - linux-libc-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - freeglut3-dev
  artifacts:
    paths:
      - projects\gmake_linux\bin\**\fts_remote_console\
      - projects\gmake_linux\bin\**\example_game\

branches:
  only:
    - master

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which g++-4.9) /usr/bin/g++; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which gcc-4.9) /usr/bin/gcc; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi
  - make config=release64

notifications:
  email: false

deploy:
  provider: s3
  access_key_id: AKIAJHCSHBXX3TPZMHIA
  secret_access_key:
    secure: UkdI9pPtmG95vTebGSajc6bBKwulFft0wQheiCsoKdlLY/mb4CHYs5cFWI4zkSNpBo9vGCk/lfYK5Hs7Vpi7fEGgfPEC1kseRQ3JTJdpI0I7vACkzrqWYkCP50pnY3OcaTmzjs238e1kc2Dr8acXjNyaDMsTYjaYWFcvuCtNUxv3TpO73v+nVPe391KpTv/vjSnWxX7vWoTr3ZaPzBhy7a/hQ/6tSvbePm7WXy7zlQehFfC5oTa/zaoeU5GUHLpLtTD8LP4iCjCaMruhLd4kk5VGG/951glXhx+2jHD+NMnK7N6bvLzOciyKu7kX3biJhD7lq4UloT0E2eh1BbQqIB8vSfYQ87XnxaRX977CT3zT0L03vGOrdsvhcd2BoCZSpBS9iboMsvLsXJDHvbbk1+6uOBk0hR0Z4i3g6qg7SiJu17Tz6wnWueZpC7kU3B176osEZyoDJNA9cNBo4+9lWWCzT/WBbWnab4X0BVqYxCZHgLbeYeTOoW+N4y9sKtsdsXa3pKxGoaVZWqZN095Q9Ahkh7pZGM6FSffuHMeu6w+OIJaX+kV2xbfWOkh+KvPjc25j1st7XeSwid/N5G6YsA1HRKbm7xJ+qlK+ePYobf3rvbWMN18ykL09EAewk94PeqJxQJPDx/J7OKdUzVWFxFia2VH5MUATTQ2ZrUXSfjY=
  bucket: forrestthewoods.binaries
  skip_cleanup: true
  acl: public_read
