language: cpp

matrix:
  include:
      - os: linux
        compiler: gcc
        env: cxx=g++-4.9 cc=gcc-4.9
      
      - os: linux
        compiler: clang
        env: cxx=clang++-3.6 cc=clang-3.6

      - os: osx
        compiler: gcc
        env: cxx=g++-4.9 cc=gcc-4.9

      - os: osx
        compiler: clang
        env: cxx=clang++-3.6 cc=clang-3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
    - clang++-3.6
    - linux-libc-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - freeglut3-dev

branches:
  only:
    - master

script:
  - gcc --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi
  - make config=release64

notifications:
  email: false

