dist: trusty

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.6

branches:
  only:
    - master

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
  - gcc --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi
  - make all

notifications:
  email: false
