language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
    - linux-libc-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - freeglut3-dev


branches:
  only:
    - master

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which g++-4.9) /usr/bin/g++; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s -v -f $(which gcc-4.9) /usr/bin/gcc; fi

script:
  - gcc --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd projects/gmake_linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd projects/gmake_macosx; fi
  - make config=release64

notifications:
  email: false

