shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

platform:
  - Win32
  - x64

configuration:
  - debug
  - release

build:
  project: ./projects/$(TOOLSET)/fts_console.sln

artifacts:
  - path: ./projects/$(TOOLSET)/bin/x32_$(configuration)/**/*.exe
    name: test32

  - path: ./projects/$(TOOLSET)/bin/x64_$(configuration)/**/*.exe
    name: test64

notifications:

  # Email
  - provider: Email
    to:
      - lordcecil@gmail.com
    subject: 'fts_remote_console Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true